language: node_js
sudo: false
node_js:
  - 10
install:
  - npm ci
jobs:
  include:
    - stage: test
      script: npm run lint
      script: npm run test
    - stage: build
      script: npm run build:es2015
    - stage: deploy
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$NPM_API_TOKEN"
      skip_cleanup: true
      on:
        branch: master
notifications:
  email:
    on_success: change
    on_failure: always
