language: node_js
sudo: false
node_js:
  - 10
install:
  - npm ci
jobs:
  include:
    - stage: "Tests"
      script: npm run lint
      script: npm run test
    - stage: "Build"
      script: npm run build:es2015
notifications:
  email:
    on_success: change
    on_failure: always
