language: node_js
version: 1.0
sudo: false
node_js:
  - 10
before_script:
  - npm run build:es2015
install:
  - npm ci
stages:
  - test
  - deploy_to_github_pages
  - deploy_to_npm
jobs:
  include:
    - stage: test
      script: npm run lint
      script: npm run test
    - stage: deploy_to_github_pages
      deploy:
        edge: true
        provider: pages
        skip_cleanup: true
        github_token: "$GITHUB_TOKEN"
        keep_history: true
        local_dir: "./docs"
        on:
          branch: master
    - stage: deploy_to_npm
      deploy:
        edge: true
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_API_TOKEN"
        skip_cleanup: true
        on:
          branch: master
notifications:
  email:
    on_success: change
    on_failure: always
