import operationClearAll from '.';
import IDENTIFIER_CLEAR_ALL from './identifier';
import {
  KEY_ENTITY_NAME,
  KEY_IDENTIFER,
  KEY_PAYLOAD,
  KEY_TYPE,
} from '../../util/deltaCreator/constants';

describe('operationClearAll', () => {
  it('Should generate delta objects', () => {
    const strEntityName = 'entity_name';
    const opClearAll = operationClearAll(strEntityName);

    const objCreatedDelta = opClearAll.createDelta();

    expect(objCreatedDelta).toEqual({
      [KEY_ENTITY_NAME]: strEntityName,
      [KEY_IDENTIFER]: IDENTIFIER_CLEAR_ALL,
      [KEY_PAYLOAD]: {},
      [KEY_TYPE]: `reduxvita_autogenerated_${strEntityName}_${IDENTIFIER_CLEAR_ALL}`,
    });
  });

  it('Should clear an undefined state', () => {
    const strEntityName = 'entity_name';
    const opClearAll = operationClearAll(strEntityName);

    const objCreatedDelta = opClearAll.createDelta();

    expect(opClearAll.getReducerStateAfterProcessingDelta(undefined, objCreatedDelta))
      .toEqual({});
  });

  it('Should clear a set state', () => {
    const strEntityName = 'entity_name';
    const opClearAll = operationClearAll(strEntityName);

    const objCreatedDelta = opClearAll.createDelta();

    const objInitialState = {
      field_a: 1,
      field_b: 2,
      field_c: 3,
    };

    expect(opClearAll.getReducerStateAfterProcessingDelta(objInitialState, objCreatedDelta))
      .toEqual({});
  });
});
